// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsp8wxFaQ3QSfY9tyyu08Or1bCMAUWH6M',
    appId: '1:860067090916:web:be342b1e9454c6d251b7f1',
    messagingSenderId: '860067090916',
    projectId: 'gym-management-app-b9fd9',
    authDomain: 'gym-management-app-b9fd9.firebaseapp.com',
    storageBucket: 'gym-management-app-b9fd9.firebasestorage.app',
    measurementId: 'G-VSP6Q59L71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_F54O1-iN_A-ORX9Fc5P_w89qt0KgDU',
    appId: '1:860067090916:android:e3ee37906e0178f651b7f1',
    messagingSenderId: '860067090916',
    projectId: 'gym-management-app-b9fd9',
    storageBucket: 'gym-management-app-b9fd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9WH_PlNrkvvU3P3vls5Kyq_8MPfYqgM',
    appId: '1:860067090916:ios:0a87e0f24c647e3751b7f1',
    messagingSenderId: '860067090916',
    projectId: 'gym-management-app-b9fd9',
    storageBucket: 'gym-management-app-b9fd9.firebasestorage.app',
    iosBundleId: 'com.example.gymManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI9WH_PlNrkvvU3P3vls5Kyq_8MPfYqgM',
    appId: '1:860067090916:ios:0a87e0f24c647e3751b7f1',
    messagingSenderId: '860067090916',
    projectId: 'gym-management-app-b9fd9',
    storageBucket: 'gym-management-app-b9fd9.firebasestorage.app',
    iosBundleId: 'com.example.gymManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsp8wxFaQ3QSfY9tyyu08Or1bCMAUWH6M',
    appId: '1:860067090916:web:7d9dd55d6bdfff8451b7f1',
    messagingSenderId: '860067090916',
    projectId: 'gym-management-app-b9fd9',
    authDomain: 'gym-management-app-b9fd9.firebaseapp.com',
    storageBucket: 'gym-management-app-b9fd9.firebasestorage.app',
    measurementId: 'G-5PTTPWXSZD',
  );
}
